version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  web:
    build:
      context: ./web
    ports:
      - 80:80
    depends_on:
      - api

networks:
  default:
    name: mentallize
